-- MySQL Script generated by MySQL Workbench
-- gio 24 mag 2018 10:20:34 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CategoryProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CategoryProduct` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `CategoryProduct_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_CategoryProduct1_idx` (`CategoryProduct_id` ASC),
  CONSTRAINT `fk_Product_CategoryProduct1`
    FOREIGN KEY (`CategoryProduct_id`)
    REFERENCES `mydb`.`CategoryProduct` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoryList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CategoryList` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `verifyEmailLink` CHAR(32) NULL,
  `resendEmailLink` CHAR(32) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `verify_mail_link_UNIQUE` (`verifyEmailLink` ASC),
  UNIQUE INDEX `resend_mail_link_UNIQUE` (`resendEmailLink` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`List` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `OwnerId` INT NOT NULL,
  `CategoryList` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_List_CategoryList1_idx` (`CategoryList` ASC),
  INDEX `fk_List_User1_idx` (`OwnerId` ASC),
  CONSTRAINT `fk_List_CategoryList1`
    FOREIGN KEY (`CategoryList`)
    REFERENCES `mydb`.`CategoryList` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_User1`
    FOREIGN KEY (`OwnerId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shop` (
  `id` INT NOT NULL,
  `Lat` DOUBLE NOT NULL,
  `Lng` DOUBLE NOT NULL,
  `Category` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Shop_CategoryList1_idx` (`Category` ASC),
  CONSTRAINT `fk_Shop_CategoryList1`
    FOREIGN KEY (`Category`)
    REFERENCES `mydb`.`CategoryList` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductInList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductInList` (
  `Product_id` INT NOT NULL,
  `List_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProductInList_List1_idx` (`List_id` ASC),
  CONSTRAINT `fk_ProductInList_Product`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductInList_List1`
    FOREIGN KEY (`List_id`)
    REFERENCES `mydb`.`List` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `User_id` INT NOT NULL,
  `List_id` INT NOT NULL,
  `text` VARCHAR(256) NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_List1_idx` (`List_id` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_List1`
    FOREIGN KEY (`List_id`)
    REFERENCES `mydb`.`List` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permission` (
  `List_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `addObject` TINYINT NOT NULL,
  `deleteObject` TINYINT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Permissi_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Permissi_List1`
    FOREIGN KEY (`List_id`)
    REFERENCES `mydb`.`List` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permissi_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notifica` (
  `id` INT NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `stato` TINYINT NOT NULL,
  `User_id` INT NOT NULL,
  INDEX `fk_Notifica_User1_idx` (`User_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Notifica_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Log` (
  `Product_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `last1` DATETIME NOT NULL,
  `last2` DATETIME NULL,
  `last3` DATETIME NULL,
  `last4` DATETIME NULL,
  `id` INT NOT NULL,
  INDEX `fk_Log_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Log_User1_idx` (`User_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Log_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Log_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
